Making new datasets to Ashleys reccomendation to try out.

This includes combining the 15% and 2nd datasets and removing 1/10 as a testing set

In [1]:
import time
import numpy as np
import torch
import torch.nn as nn
from partd.utils import framesplit
from torch.utils.data import DataLoader
from itertools import product
from collections import OrderedDict, namedtuple
import torchvision.transforms as transforms
from PIL import Image
#import csv
from torch.utils.tensorboard import SummaryWriter

In [2]:
#load in the data
data_15 = np.load("A:/3rd_Year_Project/Project_code/data/Siamese_dataset/15.npz")
data_2nd = np.load("A:/3rd_Year_Project/Project_code/data/Siamese_dataset/2nd.npz")

framenumber_15 = np.load("A:/3rd_Year_Project/Project_code/data/Cropped_and_variable_labels/framenumber15.npy")
framenumber_2nd = np.load("A:/3rd_Year_Project/Project_code/data/Cropped_and_variable_labels/framenumber2nd.npy")

data_15_img = data_15['images']
data_2nd_img = data_2nd['images']

data_15_label = data_15['labels']
data_2nd_label = data_2nd['labels']

In [4]:
print(data_15_img.shape)

(12619, 128, 128)


In [8]:
#combine the datasets
combined_label = np.concatenate((data_15_label, data_2nd_label), axis=0)
combined_frame = np.concatenate((framenumber_15, framenumber_2nd), axis=0)
combined_image = np.concatenate((data_15_img, data_2nd_img), axis=0)

print(combined_image.shape)
print(combined_label.shape)
print(combined_frame.shape)

np.savez_compressed(r"A:\3rd_Year_Project\Project_code\data\Combined_datasets\all_data.npz", images = combined_image, labels = combined_label, frames = combined_frame)

(21080, 128, 128)
(21080,)
(21080,)


In [185]:
combined_image[3].shape
print(combined_image[3, :, :])
result = np.concatenate((combined_image[3, :, :][np.newaxis, :, :],
                         combined_image[4, :, :][np.newaxis, :, :]), axis=0)

# Check the result shape
print(result.shape)  # Expected shape: (2, 128, 128)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(2, 128, 128)


In [215]:
#select the test indexes & get test data
index_list = [] #create a list called index_list

while len(index_list) < combined_label.shape[0]/10: #While size of index list is less than 1/10 of the size of the combined label data.
    index = np.random.choice(combined_label.shape[0]) #Select a random number between 1 and the size of the combined label data, this will be the index of interest.
    if index not in index_list: #Check if index is not alread inside of index_list
        index_list.append(index) #If this index is not already in index list, append the new index to index list.
index_list.sort() #Sort the index list into ascending order

#print(index_list)

imagesArray1 = []
labelsArray1 = []
framesArray1 = [] #create these 3 lists

for index in index_list: #for all of the numbers in the index_list
    imagesArray1.append(combined_image[index]) #append the image of the index in combined data
    labelsArray1.append(combined_label[index]) #append the label of the index in combined label
    framesArray1.append(combined_frame[index]) #append the framenumber of the index in the combined data
imagesArray1 = np.array(imagesArray1)
labelsArray1 = np.array(labelsArray1)
framesArray1 = np.array(framesArray1) #turn all 3 into a numpy array

print(imagesArray1.shape)
print(labelsArray1.shape)
print(framesArray1.shape) #print shapes


imagesArray = []
labelsArray = []
framesArray = [] #make 3 new lists

for i in range(combined_label.shape[0]): #for all numbers in the size of the labels
    if i not in index_list: #if the number was not in the index list
        imagesArray.append(combined_image[i])
        labelsArray.append(combined_label[i])
        framesArray.append(combined_frame[i]) #append the image, label, frame of the index not in the index list to the new lists
imagesArray = np.array(imagesArray)
labelsArray = np.array(labelsArray)
framesArray = np.array(framesArray) #turn them into numpy arrays

print(imagesArray.shape)
print(labelsArray.shape)
print(framesArray.shape) #print the sizes of the arrays

print(combined_label.shape[0] - labelsArray1.shape[0]) #print the size of the expected size of the training dataset

#save the data
np.savez_compressed(r"A:\3rd_Year_Project\Project_code\data\Combined_datasets\train_data.npz", images = imagesArray, labels = labelsArray, frames = framesArray) #save the train dataset
np.savez_compressed(r"A:\3rd_Year_Project\Project_code\data\Combined_datasets\test_data.npz", images = imagesArray1, labels = labelsArray1, frames = framesArray1) #save the test dataset

(2108, 128, 128)
(2108,)
(2108,)
(18972, 128, 128)
(18972,)
(18972,)
18972


This extra bit is being made to allow for the addition of framenumber to the 15.npz and 2nd.npz files

In [3]:
import numpy as np
data_15 = np.load("A:/3rd_Year_Project/Project_code/data/Siamese_dataset/15.npz")
data_2nd = np.load("A:/3rd_Year_Project/Project_code/data/Siamese_dataset/2nd.npz")

summertime_song_is_good = data_15["images"]
It_is_stuck_in_my_head = data_2nd["images"]

And_I_am_jamming_to_it = data_15["labels"]
Insert_humming_with_bopping_to_the_beat_here = data_2nd["labels"]

framenumber_15 = np.load("data/Cropped_and_variable_labels/framenumber15.npy")
framenumber_2nd = np.load("data/Cropped_and_variable_labels/framenumber2nd.npy")

#ok, now serious file names because boring = good and efficient, but that song is great and I am happy it is stuck in my head
images_15 = summertime_song_is_good
images_2nd = It_is_stuck_in_my_head
labels_15 = And_I_am_jamming_to_it
labels_2nd = Insert_humming_with_bopping_to_the_beat_here
framenumber_15 = framenumber_15 # just for completeness
framenumber_2nd = framenumber_2nd

print(framenumber_15.shape)
print(framenumber_2nd.shape)
print(labels_15.shape)
print(labels_2nd.shape)

np.savez_compressed(r"A:\3rd_Year_Project\Project_code\data\0. FINAL_DATASETS_I_PROMISE\15.npz", images = images_15, labels = labels_15, frames = framenumber_15)
np.savez_compressed(r"A:\3rd_Year_Project\Project_code\data\0. FINAL_DATASETS_I_PROMISE\2nd.npz", images = images_2nd, labels = labels_2nd, frames = framenumber_2nd)

(12619,)
(8461,)
(12619,)
(8461,)
